spring:
  datasource:
#    initialize: false
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moviedb
    username: sa
    password: null
  h2:
    console:
      enabled: true  
      
